backend:
  name: git-gateway
  branch: main  # The branch where your content files are stored

media_folder: "assets/uploads"   # Folder where images will be stored
public_folder: "/assets/uploads"   # Public URL for these images

collections:
  - name: "subsections"
    label: "Subsections"
    folder: "content/subsections"  # Folder where your content will be saved
    create: true                   # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields:
      - { label: "Section", name: "section", widget: "select", options: ["section1", "section2", "section3"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Images", name: "images", widget: "list", allow_add: true, fields: [
            { label: "Image", name: "image", widget: "image" },
            { label: "Caption", name: "caption", widget: "string" },
            { label: "Caption Font", name: "captionFont", widget: "string", default: "inherit" },
            { label: "Caption Color", name: "captionColor", widget: "string", default: "#000000" }
          ]
        }
